### PR TITLE
guard against naked IP

### PR DESCRIPTION
**Pull request by SHuang-Broad**
a safeguard, otherwise getting an "Unsupported protocol" error.

I'm not familiar with golang, so please provide critical feedbak.

Thanks!

### CODE REVIEW

**Comment by dinvlad** [comment]
Could you clarify on the purpose here, particularly for HTTPS? I think if an IP is used instead of a DNS name, then HTTPS shouldn't work.. So this could only work with HTTP then (which is considered insecure..)

**Comment by SHuang-Broad** [comment]
I don't fully understand the http vs https, so I just tried both. So based on your input, https should never work an IP address is given. I'll update the code accordingly.

The context:
I last used this repo about a year ago, when the cromwell server url is given in the form of `https://dsde-methods-blah`. But since then we (long reads team in methods) have a custom cromwell server set up and we didn't have a host name for it (or I just don't know the host name). Instead I have the IP and port number for it. So this morning when I tried to use this repo to upload some metadata stored in the DB attached to that server, I got an error.

Does this answer your question, Denis?

**Comment by SHuang-Broad** [comment]
Oh, and the server hides behind the Broad VPN.

**Comment by dinvlad** [comment]
I see, so you're running this code not inside a cloud function (which was its initial goal) but instead from your laptop using an `http://<ip>:<port>/bla` URL? This is a valid use case of course, although I'd still recommend using a real HTTPS URL (even for a server behind the VPN) so that you're protected against MITM attacks (however unlikely they might be).

**Comment by SHuang-Broad** [comment]
That's right.

What do I need to do to make that happen? Should the server be reconfigured?

**Comment by dinvlad** [comment]
So
1) without HTTPS, I'd recommend not doing what you're doing in this PR but rather just use an `http://<ip>:<port>` URL instead of `<ip>:<port>`. This way there's no need to modify the code to make it work in this case.
2) if you'd like to enable HTTPS, then we'd need to coordinate with who's in charge of your Cromwell server to set up a certificate for it. This might be more complex though, so it might be "fine" to just use (1) if you feel it would add too much work to enable HTTPS.

**Comment by SHuang-Broad** [comment]
I see.
What you are suggesting makes more sense.

Thanks!

**Comment by dinvlad** [comment]
My only concern is if your Cromwell server is not located on-prem but is in GCP, then we should rather enable HTTPS (even though it's firewalled, but the actual unencrypted connection is still going through the public internet then..)

**Comment by SHuang-Broad** [comment]
It is indeed on GCP...
I have no idea how to configure a Cromwell server, @jonn-smith maintains that for us.

**Comment by dinvlad** [comment]
OK! Let's follow-up privately on Slack about that

**Pull request closed without merging**
