### PR TITLE
trivial patch to allow for a longer timeout in http requests 

### PR DESCRIPTION
**Pull request by SHuang-Broad**
to Cromwell servers

### CODE REVIEW

**Comment by dinvlad** [comment]
Perfect, thank you!

**Comment by dinvlad** [comment]
One other improvement to consider adding is retries for http calls. There's a package for exponential retries for Go that we've used successfully for this purpose in other projects: https://github.com/hashicorp/go-retryablehttp

**Comment by SHuang-Broad** [comment]
Yes. The cromwell server we (methods) are using is not super stable, therefore retries are probably necessary for other servers as well. We actually have a batch lunch script that does just that, retries....

**Comment by dinvlad** [comment]
Cool! Lmk and we can possibly draft a PR sometime in the next few weeks.

**Pull request merged**
